# Configuración optimizada para EasyPanel - Forzar redeploy
[variables]
NODE_ENV = "production"
PORT = "4173"

[phases.build]
cmd = "npm run build"

[phases.start]
cmd = "serve -s dist -l tcp://0.0.0.0:$PORT"